- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Remove default site
  file:
    path: "{{ nginx_sites_enabled_path }}/default"
    state: absent
  when: nginx_remove_default_site | bool
  notify: reload nginx

- name: Create Laravel vhost from template
  template:
    src: laravel.conf.j2
    dest: "{{ nginx_sites_available_path }}/{{ nginx_site_name }}"
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable Laravel site
  file:
    src: "{{ nginx_sites_available_path }}/{{ nginx_site_name }}"
    dest: "{{ nginx_sites_enabled_path }}/{{ nginx_site_name }}"
    state: link
  notify: reload nginx
