---
# Nginx configuration
nginx_remove_default_site: true

# Laravel site configuration
nginx_server_name: "_"
nginx_root_path: "/var/www/laravel/public"
nginx_php_fpm_socket: "unix:/run/php/php8.3-fpm.sock"
nginx_listen_port: 80

# Site configuration
nginx_site_name: "laravel"
nginx_sites_available_path: "/etc/nginx/sites-available"
nginx_sites_enabled_path: "/etc/nginx/sites-enabled"
